-- Enable the vector extension if not already enabled
create extension if not exists vector;

-- Create the table directly
create table if not exists huggingface_embeddings (
    id bigint generated by default as identity primary key,
    kurskode text not null,
    kursnavn text,
    credits text,
    level_of_study text,
    academic_coordinator text,
    ansvarlig_institutt text,
    ansvarlig_område text,
    undv_språk text,
    portfolio text,
    learning_outcome_knowledge text,
    learning_outcome_skills text,
    learning_outcome_general_competence text,
    course_content text,
    embedding vector(512),
    embedding_model text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for similarity search
create index if not exists huggingface_embeddings_embedding_idx 
on huggingface_embeddings 
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- Create unique constraint on kurskode
alter table huggingface_embeddings 
drop constraint if exists huggingface_embeddings_kurskode_key;

alter table huggingface_embeddings 
add constraint huggingface_embeddings_kurskode_key 
unique (kurskode); 